services:
  - type: web
    name: two-factor-authentication-demo-backend
    runtime: docker
    plan: free
    dockerfilePath: infra/backend.Dockerfile
    dockerContext: .

  - type: web
    name: two-factor-authentication-demo-frontend
    runtime: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
