spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: backend
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      database: ${MONGODB_DATABASE:spring-boot-jwt-auth}
      port: ${MONGODB_PORT:27018}

  mongodb:
    embedded:
      version: 5.0.5

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

server:
  port: ${SERVER_PORT:8081}

app:
  cors:
    allowed-origins: ${FRONTEND_ORIGIN:http://localhost:3000}

security:
  jwt:
    header: ${JWT_HEADER:Authorization}
    prefix: ${JWT_PREFIX:Bearer}
    expiration: ${JWT_EXPIRATION:86400}
    secret: ${JWT_SECRET}
